CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE parking_spaces (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SpaceNumber" integer NOT NULL,
    "IsAvailable" boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT "PK_parking_spaces" PRIMARY KEY ("Id")
);

CREATE TABLE parking_sessions (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "VehicleType" integer NOT NULL,
    "VehicleReg" character varying(10) NOT NULL,
    "ParkingSpaceId" integer NOT NULL,
    "TimeIn" timestamp with time zone NOT NULL,
    "TimeOut" timestamp with time zone,
    "IsActive" boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT "PK_parking_sessions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_parking_sessions_parking_spaces_ParkingSpaceId" FOREIGN KEY ("ParkingSpaceId") REFERENCES parking_spaces ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_parking_sessions_ParkingSpaceId" ON parking_sessions ("ParkingSpaceId") WHERE "TimeOut" IS NULL;

CREATE UNIQUE INDEX "IX_parking_sessions_VehicleReg" ON parking_sessions ("VehicleReg") WHERE "TimeOut" IS NULL;

CREATE UNIQUE INDEX "IX_parking_spaces_SpaceNumber" ON parking_spaces ("SpaceNumber");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260625192139_InitialMigration', '10.0.9');

COMMIT;