namespace CarParking.Api.Data.Entities;

public class ParkingSpace
{
    // identity column (generated by default as identity)
    public virtual int Id { get; set; }
    public virtual int SpaceNumber { get; set; }
    public virtual bool IsAvailable { get; set; }
}
