namespace CarParking.Api.Data.Entities;

public class ParkingSession
{
    // identity column (generated by default as identity)
    public virtual int Id { get; set; }
    public virtual VehicleType VehicleType { get; set; }
    public virtual string VehicleReg { get; set; } = string.Empty;
    public virtual ParkingSpace ParkingSpace { get; set; } = null!;
    public virtual DateTime TimeIn { get; set; } //with timezone offset
    public virtual DateTime? TimeOut { get; set; } //with timezone offset
    public virtual bool IsActive { get; set; }
}